# Generated by Django 4.1.5 on 2023-01-03 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatToDad_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatToDad_app.post')),
                ('user_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatToDad_app.author')),
            ],
        ),
    ]
