# Generated by Django 4.1.5 on 2023-01-07 23:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatToDad_app', '0002_postlikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200, unique=True)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('addressNumber', models.IntegerField()),
                ('addressStreet', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(max_length=200, unique=True)),
                ('zip', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatToDad_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('activity_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatToDad_app.activity')),
            ],
        ),
    ]
