# Generated by Django 4.1.3 on 2023-01-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatToDad_app', '0002_postlikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlikes',
            old_name='post_Id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='user_Id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(related_name='likes', to='whatToDad_app.author'),
        ),
    ]
