# Generated by Django 4.1.5 on 2023-01-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatToDad_app', '0002_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(to='whatToDad_app.topic'),
        ),
    ]
