# Generated by Django 4.1.4 on 2023-03-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatToDad_app', '0004_postcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
