# Generated by Django 4.1.5 on 2023-01-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatToDad_app', '0004_alter_activitycomments_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='activitycomments',
            old_name='activity_Id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='post_Id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='user_Id',
            new_name='user',
        ),
    ]
