# Generated by Django 4.1.5 on 2023-01-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatToDad_app', '0006_alter_activity_addressstreet_alter_activity_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='user',
            new_name='author',
        ),
    ]
