# Generated by Django 4.1.5 on 2023-01-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatToDad_app', '0007_alter_activity_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
